BEGIN;

ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_26a_status TEXT DEFAULT 'tidak';
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_26c_status TEXT DEFAULT 'tidak';
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_26c_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_26d_status TEXT DEFAULT 'tidak';
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_26d_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_26e_status TEXT DEFAULT 'tidak';
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_26e_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_26f_status TEXT DEFAULT 'tidak';
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_26f_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_33e_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_33f_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_38b_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_43a_status TEXT DEFAULT 'tidak';
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_43b_status TEXT DEFAULT 'tidak';
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_43c_status TEXT DEFAULT 'tidak';
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_43d_status TEXT DEFAULT 'tidak';
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_43e_status TEXT DEFAULT 'tidak';

ALTER TABLE aspect_c ADD COLUMN IF NOT EXISTS ind_2a_program INTEGER DEFAULT 0;
ALTER TABLE aspect_c ADD COLUMN IF NOT EXISTS ind_2a_indikator INTEGER DEFAULT 0;
ALTER TABLE aspect_c ADD COLUMN IF NOT EXISTS ind_2b_program INTEGER DEFAULT 0;
ALTER TABLE aspect_c ADD COLUMN IF NOT EXISTS ind_2b_indikator INTEGER DEFAULT 0;

CREATE TABLE IF NOT EXISTS assessment_files (
  id SERIAL PRIMARY KEY,
  kecamatan_id INTEGER NOT NULL REFERENCES kecamatan(id) ON DELETE CASCADE,
  instrument TEXT NOT NULL,
  indicator_key TEXT NOT NULL,
  original_name TEXT NOT NULL,
  stored_name TEXT NOT NULL UNIQUE,
  mime_type TEXT,
  size_bytes INTEGER DEFAULT 0,
  uploaded_by INTEGER REFERENCES kecamatan(id),
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_assessment_files_owner
  ON assessment_files(kecamatan_id, instrument, indicator_key);

COMMIT;
