BEGIN;

CREATE TABLE IF NOT EXISTS assessment_progress (
  kecamatan_id INTEGER NOT NULL REFERENCES kecamatan(id) ON DELETE CASCADE,
  instrument TEXT NOT NULL,
  filled_fields TEXT NOT NULL DEFAULT '[]',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (kecamatan_id, instrument)
);

ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_28a_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_28b_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_29a_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_29b_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_30a_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_30b_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_30_klasifikasi TEXT;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_31a_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_31b_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_32a_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_32b_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_34a_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_34b_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_35a_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_35b_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_36a_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_36b_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_37a_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_37b_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_38_persen REAL DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_39a_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_39b_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_40a_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_b ADD COLUMN IF NOT EXISTS ind_40b_jumlah INTEGER DEFAULT 0;
ALTER TABLE aspect_d ADD COLUMN IF NOT EXISTS ind_2_detail TEXT;

UPDATE config SET value = '2026-12-31', updated_at = CURRENT_TIMESTAMP
WHERE key = 'deadline' AND value = '2025-12-31';

COMMIT;
